---

- name: change_pass_user
  shell: "ilorest login {{ host_ip }} -u {{ ilo_username }} -p {{ ilo_password }} && ilorest iloaccounts changepass {{ target_username }} {{ secret_obj_value }} && ilorest logout"
  connection: local
  become: no
  delegate_to: localhost
