---

- name: set_ntp_server
  shell: "ilorest login {{ host_ip }} -u {{ ilo_username }} -p {{ ilo_password }} && ilorest set StaticNTPServers=[{{ ntp_servers }}]  --selector DateTime --commit && ilorest logout"
  connection: local
  become: no
  delegate_to: localhost
