---

- name: set_ntp_server
  shell: "ilorest login {{ host_ip }} -u {{ ilo_username }} -p {{ ilo_password }} && ilorest set Oem/Hpe/RemoteSyslogServer={{ logserver }} Oem/Hpe/RemoteSyslogEnabled=True  Oem/Hpe/RemoteSyslogPort={{logserver_port}}  --selector NetworkProtocol --commit && ilorest logout"
  connection: local
  become: no
  delegate_to: localhost
